### ISSUE TITLE
User can play a piano key

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/pitchur-perfect#1]
## ⚙️ Feature

User can play a piano key and produce that specified key sound 

## 📐 Functionality

User will be able to hear themselves playing the piano

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/132402652-a15db4f3-420c-4b5d-be96-555683cf1e5f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create keyboard layout starting from middle C. (No need to create 88-keys since the app is focused on singing)
- [x] Create the css or use an api library to import the piano keys and/or sound to the webpage
- [x] Create a variable for piano keys and use a synth from an api library to play piano keys 
- [x] For each vocal range store specific keys and frequency data
- [x] When user clicks a key on the piano the piano will produce a sound

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
