### ISSUE TITLE
User can favorite their recordings

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/pitchur-perfect#10]
## ⚙️ Feature

User can favorite individual recordings
## 📐 Functionality

When the user clicks a heart on the recordings view, it will add/remove that recording from the favorites table 
## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/132417019-a0a29f7e-2519-4f19-aec3-83603586eba8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] Update `server/index.js` to add data into the favorite table on the db, and if a recording is deleted to first, delete data from the favorites table and then proceed to delete the data from the recordings table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the view component to add hearts to the recording view
- [x] If the recording has been favorited display that on the view (without the need to click on the recording) 
- [x] A favorited recording will be added to the favorite recordings table

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
