### ISSUE TITLE
User can view their favorites

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/pitchur-perfect#11]
## ⚙️ Feature

The user will be able to view their favorited recordings 
## 📐 Functionality

When the user hops into his account page home, the icon for the user will change to a heart and that heart will take the user into the favorited recordings page (the heart will change back to the user icon), and the user will be able to view and play all their recordings from their favorites

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/132417525-5c6da053-609f-48ac-8924-6a93beb88b2f.png)
![image](https://user-images.githubusercontent.com/50930123/132417545-94d2df78-c479-4c00-bdac-d8a275d590c2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to retrieve the favorites and then the url of those favorited recordings
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update the page view component to only have the favorited recordings
- [ ] User can unfavorite recordings and that will remove the recording from the favorites table 

### 🧑‍⚕️ Clean Up
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
