### ISSUE TITLE
User can match the piano keys with their pitch

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/pitchur-perfect#13]
## ⚙️ Feature

User can match the piano keys with their pitch
## 📐 Functionality

The user clicks on a piano key within their range, and a gray dot will be placed on that key to indicate the key they need to hit, and a red dot to indicate the pitch they are currently on.
## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/132418430-0f0edb72-2b1d-4977-a3c0-252a019dfe0f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

-[ ] Grab the last hit piano key object containing note, frequency, and octave
-[ ] Once the note has been grabbed project it on the display with frequency
-[ ] The note will stay up there until the user pushes another key on the piano
-[ ] Create a function where if the user is singing within a certain amount of frequency 3hz or 2hz away, either up or down the a state value of isHitting will turn true
-[ ] when isHitting is true the note will change to green
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
