### ISSUE TITLE
User can view their pre-recorded recordings

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/pitchur-perfect#7]
## ⚙️ Feature

The user will be able to see his pre-recorded recordings

## 📐 Functionality

When the user clicks the account icon he will be able to view his previous voice recordings 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/132415487-a388a96d-3546-4afd-8010-ec67c50122f0.png)
![image](https://user-images.githubusercontent.com/50930123/132415520-25c62cd3-c37f-46bf-b545-d69fc012bc07.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to retrieve recordings based on the userId and retrieve url, length, and data
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create a hashrouting when the user clicks on the user icon it will be taken to their page
- [x] Create a component that displays recording data to the user
- [x] fetch the request from server displaying title, day, and the length of the recording
event data from the database containing the url of the recording that the user clicks play on 
- [x] Make the footer to be fixed so that it is always available in mobile view
- [x] Create a component specifically for the recordings and pass it a props object
- [x] Create a function to create a "00:00" based off the recording length 
- [x] Create a event listener so that when the user clicks on a recording the recording opens up containing the audio
and the (like accordion)
- [x] Style component based off of figma
- [x] Create a function that retrieves the day and translates it into standard time "9/12/21" 
- [x] Create a margin for the footer so the elements above aren't over shadowed
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
